version: "3.9"

services:
  

  db:
    image: postgres:13
    command: -c 'max_connections=5000'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - database
  
  fileloader:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - database


volumes:
  postgres_data:

networks:
  database:
    driver: bridge
